###### 1.	Represent the above data in a 10x2 array. In each row, the first element should contain day number and second element should contain steps walked.


In [1]:
import numpy as np
import pandas as pd
arr = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

###### 2.  Lee notices that the tracker’s battery dies every day at 7 pm. Lee discovers that on an average, he walks 2000 steps every day after 7 pm. Perform an appropriate operation on your array to add 2000 steps to all the observations.


In [3]:
arr = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
new_arr = arr +  [0,2000]
new_arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

###### 3.  Write a program that returns the steps walked if the steps walked are more than 9000.


In [21]:
# steps_walked = new_arr[: , 1]
# print(steps_walked)
# index = np.where(steps_walked > 9000)
# # index
# steps_walked[index]


arr9000 = new_arr > 9000
arr9000
print(new_arr[arr9000])

steps_walked = new_arr[: , 1]

[ 9079  9230  9763 10032 11569]


###### 4. Print an array containing steps walked in sorted order.


In [22]:
print(np.sort(steps_walked))

[ 6598  7564  8012  8886  8971  9079  9230  9763 10032 11569]
