# PANDAS SERIES

Series is one-dimensional labelled array capable of holding data of any type(int,string ,float,python objects,etc),The axis labels are collectively called index

Series is nothing but a column in a excelSheet
#Syntax: pd.Series(data , index , dtype , copy)

In [22]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5])
print(ser1)
ser2 = pd.Series(['a','b','c','d','e'])
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [23]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],dtype="float64")
print(ser1)


0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [24]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(ser1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [25]:
import numpy as np
import pandas as pd
i=pd.Index(["a","b","c","d","e"])
ser1 = pd.Series([1,2,3,4,5],index=i)
print(ser1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


CREATING SERIES USING DICTIONARY

In [26]:
import numpy as np
import pandas as pd
ser1 = pd.Series({"Rohit":40,"KL":23,"Virat":100,"Panth":12,"Chahal":2})
print(ser1)


Rohit      40
KL         23
Virat     100
Panth      12
Chahal      2
dtype: int64


# DATAFRAMES

DATAFRAME IS A COLLECTION OF MULTIPLE SERIES

#pd.DataFrame(array_name , index , columns )

In [27]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)      #Numpy Array
df = pd.DataFrame(arr , index=['a','b','c'], columns=['A','B','C'])
print(df)       #Pandas DataFrame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [28]:
#A single array stores marks of one student in every subject
import numpy as np
import pandas as pd
df = pd.DataFrame([[19,20,18,16],[16,16,14,14],[20,12,13,15]], index=['Abhinav','Harshad','Gururaj'], columns=['OSA','PYTHON','JAVA','SE'])
print(df)

         OSA  PYTHON  JAVA  SE
Abhinav   19      20    18  16
Harshad   16      16    14  14
Gururaj   20      12    13  15


In [29]:
#Here, Dictionary in Dataframe ,Single arrays stores marks of every student in one subject
import numpy as np
import pandas as pd
df = pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32,24],"Java":[17,20,18,15],"SE":[12,10,18,3]}
                 ,index=[1,2,3,4]
                 )
print(df)

   Osa  Python  Java  SE
1   23      12    17  12
2   20      20    20  10
3   19      32    18  18
4   25      24    15   3


In [30]:
import numpy as np
import pandas as pd
#Error : All arrays must be of same length
df = pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32]})
print(df)


ValueError: All arrays must be of the same length

In [ ]:
import pandas as pd
ser1=pd.Series([22,10,13]) #Take index in Series
ser2=pd.Series([17,17,18,16])
df = pd.DataFrame({"OSA":ser1,"Python":ser2})#Dont take index in dictionary dataframe
print(df)

# CREATE DATAFRAME CONTAINING INFORMATION ABOUT CITIES

Possibilities of Creating Dataframe through Multiple series

1.Normal Series

2.Transpose Series

3.Dictionary Series(key == Heading , values == series)(Dont need to give name in series)

4.2-d Array (Here,a single array consists of pop and cap of one state)

In [ ]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
#print(i)
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
#print(pop)
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
#print(cap)
#pin = pd.Series(["586 101","392 479","123 456"],index = i , name = "Pin Code")
#df = pd.DataFrame([pop,cap])
#df = pd.DataFrame([pop,cap,pin]).T
df = pd.DataFrame([["7.1","Bangalore"],["12.4","Mumbai"],["8.9","Gandinagar"]],index=i,columns=["Population","Capital"])
#df =pd.DataFrame({"Population":pop,"Capital":cap,"PinCode":pin})
print(df)

# How to Add new data to a series

In [ ]:
import numpy as np
import pandas as pd
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
pop.append(pd.Series({"TamilNadu":9.8}))
#print(pop)

METHOD 1

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame([["7.1","Bangalore"],["12.4","Mumbai"],["8.9","Gandinagar"]],index=i,columns=["Population","Capital"])#DataFrame created in one line
#print(df)
print(df.append(pd.DataFrame([["5.5","Chennai"],["14.2","Hyderabad"]],index=["Tamil Nadu","Andhra Pradesh"],columns=["Population","Capital"])))

METHOD 2

In [ ]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
df = pd.DataFrame({"Population":pop,"Capital":cap})
#print(df)
print(df.append(pd.DataFrame({"Population":pd.Series([5.5,14.2],index=["Tamil Nadu","Andhra Pradesh"]),
    "Capital":pd.Series({"Tamil Nadu":"Chennai","Andhra Pradesh":"Hyderabad"})
    })
)
)

# CONCAT NEW COLUMN TO DATAFRAME

In [ ]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
pop = pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
cap= pd.Series(["Bangalore","Mumbai","Gandhinagar"], index=i, name="Capital")
df = pd.DataFrame({"Population":pop,"Capital":cap})
#print(df)
df1 = pd.concat(
    [df,pd.DataFrame({
                      "Area":pd.Series(['2.1','3.1','5.5'],index=i),
                      "CM" : pd.Series(['Bomai','Shinde','xyz'],index=i)
                  })
    ],axis=1
     )
#df1.to_csv("cities_csv")
df1 

# PANDAS SUBSETTING

In [31]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [32]:
srs = Series(np.arange(5),index=["Alpha","Beta","Gamma","Delta","Elipson"])
print(srs)

Alpha      0
Beta       1
Gamma      2
Delta      3
Elipson    4
dtype: int32


In [33]:
#In,int excluding occurs
srs[:2]

Alpha    0
Beta     1
dtype: int32

In [34]:
srs[["Beta","Gamma","Delta"]]

Beta     1
Gamma    2
Delta    3
dtype: int32

In [ ]:
#In,Series index nothing is excluded
srs["Beta":"Delta"]

In [ ]:
#print(srs)
srs[srs>3]

In [35]:
srs>3

Alpha      False
Beta       False
Gamma      False
Delta      False
Elipson     True
dtype: bool

In [37]:
srs2 = Series(["zero","one","two","three","four"],index=[3,2,4,0,1])
print(srs2)

3     zero
2      one
4      two
0    three
1     four
dtype: object


In [38]:
srs2[2:4]  #Ambiguity,it uses default indexes

4      two
0    three
dtype: object

In [ ]:
srs2.iloc[1:4]   #Uses default Indexing

In [ ]:
srs2.loc[4:1]    #uses Series indexing

In [ ]:
df = DataFrame(np.arange(21).reshape(7,3),columns=["AAA","BBB","CCC"],index=["alpha","beta","gamma","delta","elipson","zeta","eta"])
df

In [ ]:
df.AAA

In [ ]:
df['AAA']

In [ ]:
df[['BBB','CCC']]

In [ ]:
df

In [ ]:
df.iloc[1:3,1:2]  #Syntax :  df.iloc[ rows, columns]

In [ ]:
df.loc['beta':'delta','BBB':'CCC']

In [ ]:
df.iloc[:,1:3]

In [ ]:
df.iloc[:, 1:3].loc[['alpha', 'gamma', 'zeta']]

In [ ]:
df2 = df.iloc[:, 1:3].loc[['alpha', 'gamma', 'zeta']].copy()
df2

In [ ]:
df2['CCC'] = Series({'alpha':11, 'gamma':18, 'zeta':5})
df2

In [ ]:
df2.iloc[1, 1] = 2
df2

In [ ]:
df2.iloc[:, 1] = 0
df2