# PANDAS SERIES

Series is one-dimensional labelled array capable of holding data of any type(int,string ,float,python objects,etc),The axis labels are collectively called index

Series is nothing but a column in a excelSheet
#Syntax: pd.Series(data , index , dtype , copy)

In [2]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5])
print(ser1)
ser2 = pd.Series(['a','b','c','d','e'])
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [4]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],dtype="float64")
print(ser1)


0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [6]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(ser1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [9]:
import numpy as np
import pandas as pd
i=pd.Index(["a","b","c","d","e"])
ser1 = pd.Series([1,2,3,4,5],index=i)
print(ser1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


CREATING SERIES USING DICTIONARY

In [10]:
import numpy as np
import pandas as pd
ser1 = pd.Series({"Rohit":40,"KL":23,"Virat":100,"Panth":12,"Chahal":2})
print(ser1)


Rohit      40
KL         23
Virat     100
Panth      12
Chahal      2
dtype: int64


# DATAFRAMES

DATAFRAME IS A COLLECTION OF MULTIPLE SERIES

#pd.DataFrame(array_name , index , columns )

In [3]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)      #Numpy Array
df = pd.DataFrame(arr , index=['a','b','c'], columns=['A','B','C'])
print(df)       #Pandas DataFrame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [47]:
#A single array stores marks of one student in every subject
import numpy as np
import pandas as pd
df = pd.DataFrame([[19,20,18,16],[16,16,14,14],[20,12,13,15]], index=['Abhinav','Harshad','Gururaj'], columns=['OSA','PYTHON','JAVA','SE'])
print(df)

        Abhinav  Harshad  Gururaj
OSA          19       16       20
PYTHON       20       16       12
JAVA         18       14       13
SE           16       14       15


In [7]:
#Here, Dictionary in Dataframe ,Single arrays stores marks of every student in one subject
import numpy as np
import pandas as pd
df = pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32,24],"Java":[17,20,18,15],"SE":[12,10,18,3]}
                 ,index=[1,2,3,4]
                 )
print(df)

   Osa  Python  Java  SE
1   23      12    17  12
2   20      20    20  10
3   19      32    18  18
4   25      24    15   3


In [5]:
import numpy as np
import pandas as pd
#Error : All arrays must be of same length
df = pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32]})
print(df)


ValueError: All arrays must be of the same length

In [41]:
import pandas as pd
ser1=pd.Series([22,10,13]) #Take index in Series
ser2=pd.Series([17,17,18,16])
df = pd.DataFrame({"OSA":ser1,"Python":ser2})#Dont take index in dictionary dataframe
print(df)

    OSA  Python
0  22.0      17
1  10.0      17
2  13.0      18
3   NaN      16


# CREATE DATAFRAME CONTAINING INFORMATION ABOUT CITIES

Possibilities of Creating Dataframe through Multiple series

1.Normal Series

2.Transpose Series

3.Dictionary Series(key == Heading , values == series)(Dont need to give name in series)

4.2-d Array (Here,a single array consists of pop and cap of one state)

In [69]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
#print(i)
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
#print(pop)
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
#print(cap)
#pin = pd.Series(["586 101","392 479","123 456"],index = i , name = "Pin Code")
#df = pd.DataFrame([pop,cap])
#df = pd.DataFrame([pop,cap,pin]).T
df = pd.DataFrame([["7.1","Bangalore"],["12.4","Mumbai"],["8.9","Gandinagar"]],index=i,columns=["Population","Capital"])
#df =pd.DataFrame({"Population":pop,"Capital":cap,"PinCode":pin})
print(df)

            Population      Capital Pin Code
Karnataka          7.1    Bangalore  586 101
Maharashtra       12.4       Mumbai  392 479
Gujarat            8.9  Gandhinagar  123 456


# How to Add new data to a series

In [71]:
import numpy as np
import pandas as pd
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
pop.append(pd.Series({"TamilNadu":9.8}))
#print(pop)

C:\Users\CS-L2-PC10\AppData\Local\Temp\ipykernel_9704\3002736247.py:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"TamilNadu":9.8}))


Karnataka       7.1
Maharashtra    12.4
Gujarat         8.9
TamilNadu       9.8
dtype: object

METHOD 1

In [81]:
import numpy as np
import pandas as pd
df = pd.DataFrame([["7.1","Bangalore"],["12.4","Mumbai"],["8.9","Gandinagar"]],index=i,columns=["Population","Capital"])#DataFrame created in one line
#print(df)
print(df.append(pd.DataFrame([["5.5","Chennai"],["14.2","Hyderabad"]],index=["Tamil Nadu","Andhra Pradesh"],columns=["Population","Capital"])))

               Population     Capital
Karnataka             7.1   Bangalore
Maharashtra          12.4      Mumbai
Gujarat               8.9  Gandinagar
Tamil Nadu            5.5     Chennai
Andhra Pradesh       14.2   Hyderabad


C:\Users\CS-L2-PC10\AppData\Local\Temp\ipykernel_9704\3235531569.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([["5.5","Chennai"],["14.2","Hyderabad"]],index=["Tamil Nadu","Andhra Pradesh"],columns=["Population","Capital"])))


METHOD 2

In [83]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
df = pd.DataFrame({"Population":pop,"Capital":cap})
#print(df)
print(df.append(pd.DataFrame({"Population":pd.Series([5.5,14.2],index=["Tamil Nadu","Andhra Pradesh"]),
    "Capital":pd.Series({"Tamil Nadu":"Chennai","Andhra Pradesh":"Hyderabad"})
    })
)
)

               Population      Capital
Karnataka             7.1    Bangalore
Maharashtra          12.4       Mumbai
Gujarat               8.9  Gandhinagar
Tamil Nadu            5.5      Chennai
Andhra Pradesh       14.2    Hyderabad


C:\Users\CS-L2-PC10\AppData\Local\Temp\ipykernel_9704\2891639623.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population":pd.Series([5.5,14.2],index=["Tamil Nadu","Andhra Pradesh"]),


# CONCAT NEW COLUMN TO DATAFRAME