###### 1.	Represent the above data in a 10x2 array. In each row, the first element should contain day number and second element should contain steps walked.


In [1]:
import numpy as np
import pandas as pd
arr = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

###### 2.  Lee notices that the tracker’s battery dies every day at 7 pm. Lee discovers that on an average, he walks 2000 steps every day after 7 pm. Perform an appropriate operation on your array to add 2000 steps to all the observations.


In [9]:
# arr = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
new_arr = arr +  [0,2000]
new_arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

###### 3.  Write a program that returns the steps walked if the steps walked are more than 9000.


In [8]:
# steps_walked = new_arr[: , 1]
# print(steps_walked)
# index = np.where(steps_walked > 9000)
# # index
# steps_walked[index]


arr9000 = new_arr > 9000
# print(arr9000)
print(new_arr[arr9000])

steps_walked = new_arr[: , 1]

[ 9079  9230  9763 10032 11569]


###### 4. Print an array containing steps walked in sorted order.


In [10]:
sorted_arr = np.array(np.sort(steps_walked))
sorted_arr

array([ 6598,  7564,  8012,  8886,  8971,  9079,  9230,  9763, 10032,
       11569])

###### 1.Import the data into Python environment as a Pandas DataFrame.


In [18]:
import pandas as pd
df=pd.read_csv('dataset/rainfall.csv')
df.head()

STATE_UT_NAME       DISTRICT    JAN   FEB    MAR    APR  \
0  ANDAMAN And NICOBAR ISLANDS        NICOBAR  107.3  57.9   65.2  117.0   
1  ANDAMAN And NICOBAR ISLANDS  SOUTH ANDAMAN   43.7  26.0   18.6   90.5   
2  ANDAMAN And NICOBAR ISLANDS  N & M ANDAMAN   32.7  15.9    8.6   53.4   
3            ARUNACHAL PRADESH          LOHIT   42.2  80.8  176.4  358.5   
4            ARUNACHAL PRADESH     EAST SIANG   33.3  79.5  105.9  216.5   

     MAY    JUN    JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  \
0  358.5  295.5  285.0  271.9  354.8  326.0  315.2  250.9  2805.2    165.2   
1  374.4  457.2  421.3  423.1  455.6  301.2  275.8  128.3  3015.7     69.7   
2  343.6  503.3  465.4  460.9  454.8  276.1  198.6  100.0  2913.3     48.6   
3  306.4  447.0  660.1  427.8  313.6  167.1   34.1   29.8  3043.8    123.0   
4  323.0  738.3  990.9  711.2  568.0  206.9   29.5   31.7  4034.7    112.8   

   Mar-May  Jun-Sep  Oct-Dec  
0    540.7   1207.2    892.1  
1    483.5   1757.2    705.3  
2    405.6   1884.4    574.7  
3    841.3   1848.5    231.0  
4    645.4   3008.4    268.1

###### 2.Check for missing values, if any and drop the corresponding rows.


In [19]:
df.isnull().sum()

STATE_UT_NAME    0
DISTRICT         0
JAN              0
FEB              0
MAR              0
APR              0
MAY              0
JUN              0
JUL              0
AUG              0
SEP              0
OCT              0
NOV              0
DEC              0
ANNUAL           0
Jan-Feb          0
Mar-May          0
Jun-Sep          0
Oct-Dec          0
dtype: int64

In [79]:
df.dropna()

STATE_UT_NAME        DISTRICT    JAN   FEB    MAR    APR  \
0    ANDAMAN And NICOBAR ISLANDS         NICOBAR  107.3  57.9   65.2  117.0   
1    ANDAMAN And NICOBAR ISLANDS   SOUTH ANDAMAN   43.7  26.0   18.6   90.5   
2    ANDAMAN And NICOBAR ISLANDS   N & M ANDAMAN   32.7  15.9    8.6   53.4   
3              ARUNACHAL PRADESH           LOHIT   42.2  80.8  176.4  358.5   
4              ARUNACHAL PRADESH      EAST SIANG   33.3  79.5  105.9  216.5   
..                           ...             ...    ...   ...    ...    ...   
636                       KERALA          IDUKKI   13.4  22.1   43.6  150.4   
637                       KERALA        KASARGOD    2.3   1.0    8.4   46.9   
638                       KERALA  PATHANAMTHITTA   19.8  45.2   73.9  184.9   
639                       KERALA         WAYANAD    4.8   8.3   17.5   83.3   
640                  LAKSHADWEEP     LAKSHADWEEP   20.8  14.7   11.8   48.9   

       MAY    JUN     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  
0    358.5  295.5   285.0  271.9  354.8  326.0  315.2  250.9  2805.2  
1    374.4  457.2   421.3  423.1  455.6  301.2  275.8  128.3  3015.7  
2    343.6  503.3   465.4  460.9  454.8  276.1  198.6  100.0  2913.3  
3    306.4  447.0   660.1  427.8  313.6  167.1   34.1   29.8  3043.8  
4    323.0  738.3   990.9  711.2  568.0  206.9   29.5   31.7  4034.7  
..     ...    ...     ...    ...    ...    ...    ...    ...     ...  
636  232.6  651.6   788.9  527.3  308.4  343.2  172.9   48.1  3302.5  
637  217.6  999.6  1108.5  636.3  263.1  234.9   84.6   18.4  3621.6  
638  294.7  556.9   539.9  352.7  266.2  359.4  213.5   51.3  2958.4  
639  174.6  698.1  1110.4  592.9  230.7  213.1   93.6   25.8  3253.1  
640  171.7  330.2   287.7  217.5  163.1  157.1  117.7   58.8  1600.0  

[641 rows x 15 columns]

###### 3.Find the district that gets the highest annual rainfall.


In [38]:
df[['DISTRICT','ANNUAL']].sort_values(by='ANNUAL',ascending=False).head(1)

DISTRICT  ANNUAL
55  TAMENGLONG  7229.3

###### 4.Display the top 5 states that get the highest annual rainfall.


In [39]:
df[['DISTRICT','ANNUAL']].sort_values(by='ANNUAL',ascending=False).head(5)

DISTRICT  ANNUAL
55      TAMENGLONG  7229.3
47   JAINTIA HILLS  6379.9
46   EAST KHASI HI  6166.1
12     UPPER SIANG  4402.1
598          UDUPI  4306.0

###### 5.Drop the columns 'Jan-Feb', 'Mar-May', 'Jun-Sep', 'Oct-Dec'.

In [40]:
df.drop(['Jan-Feb','Mar-May','Jun-Sep','Oct-Dec'] , axis=1, inplace=True)

In [41]:
df.head()

STATE_UT_NAME       DISTRICT    JAN   FEB    MAR    APR  \
0  ANDAMAN And NICOBAR ISLANDS        NICOBAR  107.3  57.9   65.2  117.0   
1  ANDAMAN And NICOBAR ISLANDS  SOUTH ANDAMAN   43.7  26.0   18.6   90.5   
2  ANDAMAN And NICOBAR ISLANDS  N & M ANDAMAN   32.7  15.9    8.6   53.4   
3            ARUNACHAL PRADESH          LOHIT   42.2  80.8  176.4  358.5   
4            ARUNACHAL PRADESH     EAST SIANG   33.3  79.5  105.9  216.5   

     MAY    JUN    JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  
0  358.5  295.5  285.0  271.9  354.8  326.0  315.2  250.9  2805.2  
1  374.4  457.2  421.3  423.1  455.6  301.2  275.8  128.3  3015.7  
2  343.6  503.3  465.4  460.9  454.8  276.1  198.6  100.0  2913.3  
3  306.4  447.0  660.1  427.8  313.6  167.1   34.1   29.8  3043.8  
4  323.0  738.3  990.9  711.2  568.0  206.9   29.5   31.7  4034.7

###### 6.Display the state-wise mean rainfall for all the months using a pivot table.


In [55]:
st = pd.pivot_table( df, index='STATE_UT_NAME' , values=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'])
st.sample(2)

APR         AUG        DEC        FEB        JAN  \
STATE_UT_NAME                                                          
LAKSHADWEEP    48.90000  217.500000  58.800000  14.700000  20.800000   
RAJASTHAN       3.30303  194.554545   3.021212   4.721212   5.348485   

                      JUL        JUN        MAR         MAY         NOV  \
STATE_UT_NAME                                                             
LAKSHADWEEP    287.700000  330.20000  11.800000  171.700000  117.700000   
RAJASTHAN      195.278788   54.09697   3.815152   10.627273    6.254545   

                      OCT         SEP  
STATE_UT_NAME                          
LAKSHADWEEP    157.100000  163.100000  
RAJASTHAN       14.430303   86.145455

###### 7.Display the count of districts in each state.

In [61]:
df.groupby('STATE_UT_NAME')['DISTRICT'].count()

STATE_UT_NAME
ANDAMAN And NICOBAR ISLANDS     3
ANDHRA PRADESH                 23
ARUNACHAL PRADESH              16
ASSAM                          27
BIHAR                          38
CHANDIGARH                      1
CHATISGARH                     18
DADAR NAGAR HAVELI              1
DAMAN AND DUI                   2
DELHI                           9
GOA                             2
GUJARAT                        26
HARYANA                        21
HIMACHAL                       12
JAMMU AND KASHMIR              22
JHARKHAND                      24
KARNATAKA                      30
KERALA                         14
LAKSHADWEEP                     1
MADHYA PRADESH                 50
MAHARASHTRA                    35
MANIPUR                         9
MEGHALAYA                       7
MIZORAM                         9
NAGALAND                       11
ORISSA                         30
PONDICHERRY                     4
PUNJAB                         20
RAJASTHAN                      33


###### 8.For each state, display the district that gets the highest rainfall in May. Also display the recorded rainfall.

In [82]:
rr= pd.pivot_table(df, index='STATE_UT_NAME' , values=['DISTRICT','MAY'] , aggfunc=max)
rr

DISTRICT    MAY
STATE_UT_NAME                                     
ANDAMAN And NICOBAR ISLANDS   SOUTH ANDAMAN  374.4
ANDHRA PRADESH                WEST GODAVARI   96.6
ARUNACHAL PRADESH                WEST SIANG  453.0
ASSAM                         UDALGURI(DARA  604.0
BIHAR                        WEST CHAMPARAN  155.7
CHANDIGARH                       CHANDIGARH   30.1
CHATISGARH                          SURGUJA   38.6
DADAR NAGAR HAVELI                      DNH    7.4
DAMAN AND DUI                           DIU    7.4
DELHI                            WEST DELHI   19.3
GOA                               SOUTH GOA   94.3
GUJARAT                              VALSAD   12.5
HARYANA                         YAMUNANAGAR   27.9
HIMACHAL                                UNA   91.7
JAMMU AND KASHMIR                  UDHAMPUR  111.4
JHARKHAND                    WEST SINGHBHUM   86.1
KARNATAKA                            YADGIR  193.8
KERALA                              WAYANAD  300.4
LAKSHADWEEP                     LAKSHADWEEP  171.7
MADHYA PRADESH                      VIDISHA   19.9
MAHARASHTRA                        YAVATMAL   60.2
MANIPUR                              UKHRUL  539.9
MEGHALAYA                     WEST GARO HIL  733.7
MIZORAM                            SERCHHIP  351.4
NAGALAND                          ZUNHEBOTO  325.6
ORISSA                           SUNDARGARH  136.8
PONDICHERRY                           YANAM   43.6
PUNJAB                           TARN TARAN   25.6
RAJASTHAN                           UDAIPUR   20.7
SIKKIM                          WEST SIKKIM  355.4
TAMIL NADU                     VIRUDHUNAGAR  141.5
TRIPURA                        WEST TRIPURA  440.1
UTTAR PRADESH                      VARANASI   38.6
UTTARANCHAL                      UTTARKASHI  102.1
WEST BENGAL                   WEST MIDNAPOR  345.4